apiVersion: v2
name: cray-console-node
version: 0.0.0
description: Kubernetes resources for cray-console-node
keywords:
- cray-console
- cray-console-node
home: https://github.com/Cray-HPE/console-node
sources:
- https://github.com/Cray-HPE/console-node
dependencies:
- name: cray-service
  version: ^7.0.0
  repository: https://artifactory.algol60.net/artifactory/csm-helm-charts/
maintainers:
- name: dlaine-hpe
  email: laine@hpe.com
appVersion: 0.0.0
annotations:
  artifacthub.io/images: |
    - name: cray-console-node
      image: artifactory.algol60.net/csm-docker/stable/cray-console-node:0.0.0
    - name: alpine
      image: artifactory.algol60.net/docker.io/alpine:latest
  artifacthub.io/license: MIT
