apiVersion: v1
description: "Kubernetes resources for cray-console-node"
name: "cray-console-node"
home: "scms/cray-console-node"
# This version string is replaced at build time by the build prep script
version: @VERSION@
